# Generated by Django 4.0.5 on 2023-05-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_Name', models.CharField(max_length=100)),
                ('author_Name', models.CharField(max_length=100)),
                ('Desc', models.TextField()),
            ],
        ),
    ]
